title: âœ¨ Sanghun Developer Portfolio ğŸ’»
email: radon99@naver.com
description:   |  
  ì•ˆë…•í•˜ì„¸ìš”! ğŸ˜Š <br>
  ì •ìƒí›ˆì˜ ê°œë°œ í”„ë¡œì íŠ¸ì™€ ê¸°ìˆ  ì‘ì—…ë¬¼ì„ ë‹´ì€ í¬íŠ¸í´ë¦¬ì˜¤ ì‚¬ì´íŠ¸ì…ë‹ˆë‹¤. <br>
  ì„ë² ë””ë“œ, AI, í•˜ë“œì›¨ì–´ ë“± ë‹¤ì–‘í•œ í”„ë¡œì íŠ¸ë¥¼ í™•ì¸í•´ë³´ì„¸ìš”! <br>
  ğŸš€ğŸ’»âš™ï¸
  <div class='sx-button'>
  <a href='https://github.com/radon99/radon99.github.io/tree/main/projects' target="_blank">
    <img src='/assets/img/icons/github.png' style="width: auto; max-height: 50px;" />
  </a>
  </div>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://radon99.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#theme: jekyll-theme-simplex
remote_theme: andreondra/jekyll-theme-simplex
plugins:
    - jekyll-remote-theme

logo_img: /assets/img/icons/logo.png #Absolute path to the logo. If not specified, the title will be displayed instead.
copyright: Â© Sanghun 2025 #Your copyright.

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
